export const FlowCards = [
  {
    image: 'images/flowCardsContent/video preview0.png',
    title: 'Binance',
    subtitle: 'P2P Deal',
    startValue: '4.6',
    subscription: 'Crypto Exchanges • P2P',
  },
  {
    image: 'images/flowCardsContent/video preview1.png',
    title: 'Binance',
    subtitle: 'Onboarding',
    startValue: '4.8',
    subscription: 'Crypto Exchanges • Login • Verification',
  },
  {
    image: 'images/flowCardsContent/video preview2.png',
    title: 'Metamask',
    subtitle: 'Depositing Funds',
    startValue: '4.4',
    subscription: 'Personal Investments • Crypto • Wallets',
  },
  {
    image: 'images/flowCardsContent/video preview2.png',
    title: 'Metamask',
    subtitle: 'Depositing Funds',
    startValue: '4.7',
    subscription: 'Crypto Exchanges',
  },
  {
    image: 'images/flowCardsContent/video preview3.png',
    title: 'Kraken',
    subtitle: 'Onboarding',
    startValue: '4.4',
    subscription: 'Crypto Exchanges • Login • Verification',
  },
  {
    image: 'images/flowCardsContent/video preview4.png',
    title: 'Binance',
    subtitle: 'Buy crypto',
    startValue: '4.7',
    subscription: 'Crypto Exchanges • Buy Crypto',
  },
  {
    image: 'images/flowCardsContent/video preview2.png',
    title: 'Metamask',
    subtitle: 'Depositing Funds',
    startValue: '4.2',
    subscription: 'Personal Investments • Crypto • Crypto Exchanges',
  },
  {
    image: 'images/flowCardsContent/video preview2.png',
    title: 'Metamask',
    subtitle: 'Depositing Funds',
    startValue: '4.7',
    subscription: 'Personal Investments • Crypto Wallets • Crypto Exchanges',
  },
  {
    image: 'images/flowCardsContent/video preview7.png',
    title: 'Coinbase',
    subtitle: 'Onboarding',
    startValue: '4.2',
    subscription: 'Crypto Exchanges • Login • Verification',
  },
];
